-- ====== 系统配置相关表 (PostgreSQL) ======
DROP TABLE IF EXISTS sys_open_auth; DROP TABLE IF EXISTS sys_task_logs; DROP TABLE IF EXISTS sys_task; DROP TABLE IF EXISTS sys_config;
CREATE TABLE sys_config (config_id BIGSERIAL PRIMARY KEY, config_name VARCHAR(100) DEFAULT '', config_key VARCHAR(100) DEFAULT '', config_value VARCHAR(500) DEFAULT '', config_type CHAR(1) DEFAULT 'N', create_by VARCHAR(64) DEFAULT '', create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, update_by VARCHAR(64) DEFAULT '', update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, remark VARCHAR(500));
CREATE TABLE sys_task (id BIGSERIAL PRIMARY KEY, task_name VARCHAR(255), cron VARCHAR(255), method VARCHAR(255), remark VARCHAR(255), create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, status INT DEFAULT 0);
CREATE TABLE sys_task_logs (id BIGSERIAL PRIMARY KEY, task_id INT, result TEXT, start_time TIMESTAMP, end_time TIMESTAMP, status INT, create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE sys_open_auth (id BIGSERIAL PRIMARY KEY, app_key VARCHAR(25) NOT NULL, app_secret VARCHAR(255) NOT NULL, request_ip VARCHAR(255), request_time TIMESTAMP, request_count INT DEFAULT 0, white_list VARCHAR(255), status INT DEFAULT 1, remark VARCHAR(255), create_by VARCHAR(64) DEFAULT '', create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, update_by VARCHAR(64) DEFAULT '', update_time TIMESTAMP, type INT DEFAULT 0);
INSERT INTO sys_config (config_name, config_key, config_value, config_type, remark) VALUES ('系统名称', 'sys.name', '启航AI ERP', 'Y', '系统名称'),('验证码开关', 'sys.account.captchaEnabled', 'false', 'Y', '是否开启验证码功能');
INSERT INTO sys_task (id, task_name, cron, method, remark, status) VALUES (11,'推送待发货订单到供应商','-',NULL,'推送待发货订单到供应商',1),(21,'内部系统数据推送','-',NULL,'内部系统数据推送',1),(22,'三方系统数据推送','-',NULL,'三方系统数据推送',1),(23,'云仓系统数据推送','-',NULL,'云仓系统数据推送',1);
SELECT setval('sys_config_config_id_seq', (SELECT MAX(config_id) FROM sys_config)); SELECT setval('sys_task_id_seq', (SELECT MAX(id) FROM sys_task));
