spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/qihang_ai_platform
    username: postgres
    password: postgres

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY:sk-your-deepseek-api-key}

logging:
  level:
    cn.qihang.ai: DEBUG